Repository hacktoberfest-unicam/awesome-hacktoberfest-aluminum-ape, pull requests merged in 2022-10, with the labels that each got.

#8 Web Merge :)
  web/README.md
  web/redirect/Java/.gitkeep
  web/redirect/JavaScript/.gitkeep
  web/redirect/PHP/.gitkeep
  web/redirect/Python/.gitkeep
  web/redirect/README.md
  web/redirect/c_sharp/.gitkeep
  web/sql_injection/README.md
  web/sql_injection/c_sharp/.gitkeep
  web/sql_injection/java/.gitkeep
  web/sql_injection/javascript/.gitkeep
  web/sql_injection/php/.gitkeep
  web/sql_injection/python/.gitkeep
  web/strongbox/README.md
  web/strongbox/c_sharp/.gitkeep
  web/strongbox/java/.gitkeep
  web/strongbox/javascript/.gitkeep
  web/strongbox/php/.gitkeep
  web/strongbox/python/.gitkeep
  web/web_scraping/README.md
  web/web_scraping/c_sharp/.gitkeep
  web/web_scraping/java/.gitkeep
  web/web_scraping/javascript/.gitkeep
  web/web_scraping/php/.gitkeep
  web/web_scraping/python/.gitkeep
Labels: hacktoberfest-accepted

#63 Converti numero decimale in binario
  tutorial/Decimal-to-Binary/SofiaScattolini/src/Convertitor.java
Labels: hacktoberfest-accepted

#72 created pylindrome.py
  tutorial/Palindrome/cleoPinoli/pylindrome.py
Labels: hacktoberfest-accepted

#18 Add il-meme
  il-meme/stalinsort.py
Labels: hacktoberfest-accepted

#86 add mass rename
  scripting/mass-rename/piero_hierro_mass_rename/mass_rename.py
Labels: hacktoberfest-accepted

#88 git add redirect
  web/redirect/JavaScript/piero_hierro_redirect/home.html
Labels: hacktoberfest-accepted

#95 Implementato controllo palindrome
  tutorial/Palindrome/Java/Retr0mus/src/Main.java
Labels: hacktoberfest-accepted

#99 lettercount
  tutorial/LetterCount/Python/lettercount.py
Labels: hacktoberfest-accepted

#103 Gianluca Lanchini date-calculator
  algoritmi/date_calculator/Java/gianluca_lanchini_date_calculator/main.java
Labels: hacktoberfest-accepted

#94 Filippo Lampa Mass rename
  scripting/mass-rename/filippo_lampa_mass-rename/mass_rename.py
Labels: hacktoberfest-accepted

#98 Gianluca Lanchini mass-rename
  scripting/mass-rename/gianluca_lanchini_mass_rename/mass_rename.py
Labels: hacktoberfest-accepted

#112 Add files via upload
  tutorial/Palindrome/Palindrome.c
Labels: hacktoberfest-accepted

#114 Create ArraySorting.js
  tutorial/ArraySorting/JS/Lorenzo Lapucci/ArraySorting.js
Labels: hacktoberfest, hacktoberfest-accepted

#118 Create sql_injection.js
  web/sql_injection/lorenzo_lapucci/sql_injection.js
Labels: hacktoberfest, hacktoberfest-accepted

#119 Create date_calculator.js
  algoritmi/date_calculator/JS/lorenzo_lapucci/date_calculator.js
Labels: hacktoberfest, hacktoberfest-accepted

#120 Adding script: mass_rename
  scripting/mass-rename/lorenzo_lapucci/mass_rename.py
Labels: hacktoberfest, hacktoberfest-accepted

#128 Update salinsort with working code
  il-meme/HarlockOfficial-stalinsort/stalinsort.py
  il-meme/stalinsort.py
Labels: hacktoberfest, hacktoberfest-accepted

#122 Added Palindrome.java
  tutorial/Decimal-to-Binary/Converter.java
  tutorial/Palindrome/CarmineMarchesani_Palindrome/Palindrome.java
Labels: hacktoberfest-accepted

#23 Added lettercount.py
  tutorial/LetterCount/Pipperix/lettercount.py
Labels: hacktoberfest-accepted, p:lettercount

#27 Create LetterCount
  tutorial/LetterCount/SofiaScattolini/.gitignore
  tutorial/LetterCount/SofiaScattolini/src/CountCharInString.java
Labels: hacktoberfest-accepted, p:lettercount

#81 csv handler
  parsing/CSVFileParser/Python/alessandro_iena/csvhandler.py
Labels: hacktoberfest-accepted

#123 LetterCount simple solution.
  tutorial/LetterCount/SpaceCowboyS01/LetterCount.java
Labels: hacktoberfest-accepted

#126 Palindrome solution.
  tutorial/Palindrome/SpaceCowboyS01/Palindrome.java
Labels: hacktoberfest-accepted

#127 Essential Calculator.
  tutorial/SimpleCalculator/SpaceCowboyS01/SimpleCalculator.java
Labels: hacktoberfest-accepted, unranked

#132 Essential Calculator.
  tutorial/SimpleCalculator/SpaceCowboyS01/SimpleCalculator.java
Labels: hacktoberfest-accepted, unranked

#117 add DecimalToBinary.java
  tutorial/Decimal-to-Binary/piero_hierro_decimal_to_binary/DecimalToBinary.java
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#116 Letter count by Zeeeeeek - Buss_Urinometer
  tutorial/LetterCount/Zeeeeeeek - Buss_Urinometer/Counter.java
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#111 Decimal to binary
  tutorial/Decimal-to-Binary/4C4C/decToBinary.c
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#96 Add LetterCount.c
  tutorial/LetterCount/4C4C/LetterCount.c
Labels: hacktoberfest-accepted

#110 add PackProblem.java
  algoritmi/pack_problem/Java/piero_hierro_pack_problem/PackProblem.java
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#115 Gianluca Lanchini pack-problem
  algoritmi/pack_problem/Java/gianluca_lanchini_pack_problem/main.java
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#108 Added sql_injection
  web/sql_injection/php/Pipperix/index.html
  web/sql_injection/php/Pipperix/prevent_sql.php
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#107 Redirect page
  web/redirect/JavaScript/SofiaScattolini/redirect.html
  web/redirect/JavaScript/SofiaScattolini/redirect_JS.js
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#84 Equazione sec. grado
  tutorial/Second-DegreeEquation/Java/Retr0mus/src/Main.java
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#79 Palindrome
  tutorial/Palindrome/097475/palindrome.py
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#77 Calculator
  tutorial/SimpleCalculator/097475/calc.py
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#76 Sorting
  tutorial/ArraySorting/097475/Holy-Sorting.HC
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#75 redirect
  web/redirect/PHP/alessandro_iena/.gitignore
  web/redirect/PHP/alessandro_iena/index.php
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#74 Simple Calculator
  tutorial/SimpleCalculator/SofiaScattolini/src/javaCalculator.java
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#69 Added change_base.py
  algoritmi/change_base/Python/Pipperix/change_base.py
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#44 Tutorial simple calculator by Syntetize - Buss_Urinometer
  tutorial/SimpleCalculator/SimpleCalculator.java
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#39 Tutorial palindrome by Zeeeeeeek - Buss_Urinometer
  tutorial/Palindrome/Zeeeeeeek - Buss_Urinometer/PalindromeVerifier.java
Labels: hacktoberfest, hacktoberfest-accepted, rank-me-later

#130 [add] C implementation of CSV parser (Not tested, needs review)
  parsing/CSVFileParser/HarlockOfficial_csv_file_parser/linked_list.c
  parsing/CSVFileParser/HarlockOfficial_csv_file_parser/linked_list.h
  parsing/CSVFileParser/HarlockOfficial_csv_file_parser/main.c
Labels: help wanted, hacktoberfest, hacktoberfest-accepted, unranked

#60 Scripting mass rename by Zeeeeeeek - Buss_Urinometer
  scripting/mass-rename/Zeeeeeeek - Buss_Urinometer/FileRenamer.java
Labels: hacktoberfest-accepted, rank-me-later

#135 CarmineMarchesani Decimal-to-binary
  tutorial/Decimal-to-Binary/CarmineMarchesani_Decimal-to-Binary/Converter.java
Labels: hacktoberfest-accepted, unranked
